#ifndef __CANID_H
#define __CANID_H

//MITSUBISHI I-MIEV CAN MESSAGES
#define	CAN_ID_READY				0x100		// Freq: ?? 	Len: ???
#define	CAN_ID_KEY					0x101		// Freq: 10		Len: 1
#define CAN_ID_FRONT_LEFT_WHEEL		0x200		// Freq: 50		Len: 8
#define CAN_ID_BRAKE_PEDAL			0x208		// Freq: 50		Len: 8
#define CAN_ID_REAR_WHEELS			0x215		// Freq: 50		Len: 8
#define CAN_ID_BRAKE_PRESSED		0x231		// Freq: 50		Len: 8
#define CAN_ID_STEERING_WHEEL		0x236		// Freq: 10		Len: 8
#define CAN_ID_CHARGER_TEMP			0x286		// Freq: 10		Len: 8
#define CAN_ID_MOTOR_TEMP_RPM		0x298		// Freq: 10		Len: 8
#define CAN_ID_DRIVING_RANGE		0x346		// Freq: 50 	Len: 8
#define CAN_ID_AMPS_VOLTS			0x373		// Freq: 100	Len: 8
#define CAN_ID_CHARGING_STATUS		0x374		// Freq: 10		Len: 8
#define CAN_ID_AC_AMPS_VOLTS		0x389		// Freq: 10		Len: 8
#define CAN_ID_AC_STATUS			0x3A4		// Freq: 10		Len: 8
#define CAN_ID_ODOMETER				0x412		// Freq: 10		Len: 8
#define CAN_ID_GEARBOX				0x418		// Freq: 20		Len: 7
#define CAN_ID_DOOR_WINDOW			0x424		// Freq: 25		Len: 8
#define CAN_ID_GAS_PEDAL			0x696		// Freq: 10		Len: 8
#define CAN_ID_CELLINFO1			0x6E1		// Freq: 25		Len: 8
#define CAN_ID_CELLINFO2			0x6E2		// Freq: 25		Len: 8
#define CAN_ID_CELLINFO3			0x6E3		// Freq: 25		Len: 8
#define CAN_ID_CELLINFO4			0x6E4		// Freq: 25		Len: 8

//CUSTOM DEFINED CAN MESSAGES

//Messages that come from ROS and forwarded
#define CAN_ID_ROS_LIGHTS			0x400
#define CAN_ID_ROS_VELOCITY			0x500
#define CAN_ID_ROS_ACCELERATION		0x502
#define CAN_ID_ROS_DRIVE_MODE		0x520
#define CAN_ID_ROS_HANDBRAKE		0x523
#define CAN_ID_ROS_ST_WHEEL_ANGLE	0x540
#define CAN_ID_ROS_ST_OFFSET		0x542
#define CAN_ID_ROS_DOOR   			0x720

// Messages from master to drive
#define CAN_ID_MASTER_STARTUP_CHECK	0x740

// Messages from drive controller to master controller
#define CAN_ID_DRIVE_VELOCITY					0x510
#define CAN_ID_DRIVE_GAS_PEDAL					0x511
#define CAN_ID_DRIVE_GAS_PEDAL_PID				0x512
#define CAN_ID_DRIVE_GAS_PEDAL_PID_ERROR		0x513
#define CAN_ID_DRIVE_GAS_PEDAL_PID_INTEGRAL		0x514
#define CAN_ID_DRIVE_GAS_PEDAL_PID_DERIVATIVE	0x515
#define CAN_ID_DRIVE_EMERGENCY_BRAKE			0x522
#define CAN_ID_DRIVE_BRAKES_STATUS				0x533
#define CAN_ID_DRIVE_BRAKES_VALVES				0x534
#define CAN_ID_DRIVE_BRAKES_PID					0x535
#define CAN_ID_DRIVE_BRAKES_PID_ERROR			0x536
#define CAN_ID_DRIVE_BRAKES_PID_INTEGRAL		0x537
#define CAN_ID_DRIVE_BRAKES_PID_DERIVATIVE		0x538
#define CAN_ID_DRIVE_WHEEL_ANGLE	 			0x550
#define CAN_ID_DRIVE_STEERING_PID				0x551
#define CAN_ID_DRIVE_STEERING_PID_ERROR			0x552
#define CAN_ID_DRIVE_STEERING_PID_INTEGRAL		0x553
#define CAN_ID_DRIVE_STEERING_PID_DERIVATIVE 	0x554
#define CAN_ID_DRIVE_STEERING_PID_SETPOINT		0x555
#define CAN_ID_DRIVE_GEARBOX_STATUS				0x570
#define CAN_ID_DRIVE_HANDBRAKE					0x53F
#define CAN_ID_DRIVE_STARTUP_STATUS				0x750
#define CAN_ID_DRIVE_STARTUP_BRAKES				0x751
#define CAN_ID_DRIVE_STARTUP_HANDBRAKE			0x752
#define CAN_ID_DRIVE_STARTUP_GEARBOX			0x753
#define CAN_ID_DRIVE_STARTUP_STEERING			0x754
#define CAN_ID_DRIVE_STARTUP_GAS_PEDAL			0x755

#define CAN_ID_DRIVE_DRIVE						0x780

//Messages from safety controller
#define CAN_ID_SAFETY_EMERGENCY_BRAKE	0x521
#define CAN_ID_SAFETY_STEERING_PWM 		0x760
#define CAN_ID_SAFETY_GAS_VOLTAGE 		0x761
#define CAN_ID_SAFETY_GEAR_STATUS 		0x762
#define CAN_ID_SAFETY_BRAKE_PWM 		0x763
#define CAN_ID_SAFETY_BRAKE_FEEDBACK 	0x764

//Messeges from body controllers
#define CAN_ID_BODY_ULTRASONIC_FRONT	0x600
#define CAN_ID_BODY_ULTRASONIC_BACK		0x601

//CUSTOM DEFINED MESSAGES LENGTHS

//Ros
#define CAN_ID_ROS_LIGHTS_LEN 			8
#define CAN_ID_ROS_VELOCITY_LEN			4
#define CAN_ID_ROS_ACCELERATION_LEN		4
#define CAN_ID_ROS_DRIVE_MODE_LEN		1
#define CAN_ID_ROS_HANDBRAKE_LEN		1
#define CAN_ID_ROS_ST_WHEEL_ANGLE_LEN	4
#define CAN_ID_ROS_ST_OFFSET_LEN		2
#define CAN_ID_ROS_DOOR_LEN				1

//Master
#define CAN_ID_MASTER_STARTUP_CHECK_LEN	1

//Drive
#define CAN_ID_DRIVE_VELOCITY_LEN					8
#define CAN_ID_DRIVE_GAS_PEDAL_LEN					6
#define CAN_ID_DRIVE_GAS_PEDAL_PID_LEN				7
#define CAN_ID_DRIVE_GAS_PEDAL_PID_ERROR_LEN		7
#define CAN_ID_DRIVE_GAS_PEDAL_PID_INTEGRAL_LEN		7
#define CAN_ID_DRIVE_GAS_PEDAL_PID_DERIVATIVE_LEN	7
#define CAN_ID_DRIVE_EMERGENY_BRAKE_LEN				1
#define CAN_ID_DRIVE_BRAKES_STATUS_LEN				7
#define CAN_ID_DRIVE_BRAKES_VALVES_LEN				5
#define CAN_ID_DRIVE_BRAKES_PID_LEN					7
#define CAN_ID_DRIVE_BRAKES_PID_ERROR_LEN			7
#define CAN_ID_DRIVE_BRAKES_PID_INTEGRAL_LEN		7
#define CAN_ID_DRIVE_BRAKES_PID_DERIVATIVE_LEN		7
#define CAN_ID_DRIVE_WHEEL_ANGLE_LEN				7
#define CAN_ID_DRIVE_STEERING_PID_LEN				7
#define CAN_ID_DRIVE_STEERING_PID_ERROR_LEN			7
#define CAN_ID_DRIVE_STEERING_PID_INTEGRAL_LEN		7
#define CAN_ID_DRIVE_STEERING_PID_DERIVATIVE_LEN	7
#define CAN_ID_DRIVE_STEERING_PID_SETPOINT_LEN		4
#define CAN_ID_DRIVE_GEARBOX_STATUS_LEN				3
#define CAN_ID_DRIVE_HANDBRAKE_LEN 					7
#define CAN_ID_DRIVE_STARTUP_STATUS_LEN				8
#define CAN_ID_DRIVE_STARTUP_BRAKES_LEN				4
#define CAN_ID_DRIVE_STARTUP_HANDBRAKE_LEN			4
#define CAN_ID_DRIVE_STARTUP_GEARBOX_LEN			5
#define CAN_ID_DRIVE_STARTUP_STEERING_LEN			4
#define CAN_ID_DRIVE_STARTUP_GAS_PEDAL_LEN			4
#define CAN_ID_DRIVE_DRIVE_LEN						7

//Safety
#define CAN_ID_SAFETY_EMERGENCY_BRAKE_LEN	1
#define CAN_ID_SAFETY_STEERING_PWM_LEN 		8
#define CAN_ID_SAFETY_GAS_VOLTAGE_LEN 		4
#define CAN_ID_SAFETY_GEAR_STATUS_LEN 		1
#define CAN_ID_SAFETY_BRAKE_PWM_LEN 		8
#define CAN_ID_SAFETY_BRAKE_FEEDBACK_LEN 	2

//Body
#define CAN_ID_BODY_ULTRASONIC_FRONT_LEN	5
#define CAN_ID_BODY_ULTRASONIC_BACK_LEN		5

#endif /* __CANID_H */

